In [31]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
df = sns.load_dataset('iris')

In [33]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [6]:
encode=LabelEncoder()
df['species']=encode.fit_transform(df['species'])

In [35]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [36]:
df = df[['sepal_length','petal_length','species']]

In [37]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [38]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [40]:
clf = LogisticRegression(multi_class='multinomial')

In [41]:
clf.fit(X_train,y_train)

C:\Users\niles\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial')

In [42]:
y_pred = clf.predict(X_test)

In [16]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0])

In [17]:
comp={'actual':y_test,'predicted':y_pred}
print(comp)

{'actual': array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0]), 'predicted': array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 0, 0, 1, 1, 0])}

In [18]:
print(accuracy_score(y_test,y_pred))

0.9666666666666667

In [20]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0   1  2
0  11   0  0
1   0  13  0
2   0   1  5

In [22]:
quary=np.array([[3.4,2.7]])
clf.predict_proba(quary)

array([[7.72858510e-01, 2.26766581e-01, 3.74909094e-04]])

In [23]:
clf.predict(quary)

array([0])

In [30]:
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x.values, y.values, clf, legend=2)

# Adding axes annotations
plt.xlabel('sepal length [cm]')
plt.xlabel('petal length [cm]')
plt.title('Softmax on Iris')

plt.show()

AttributeError: 'numpy.ndarray' object has no attribute 'values'